import { Task } from "./kanban-types";

const id = () => Math.random().toString(36).slice(2, 10);

export const seedTasks: Task[] = [
  {
    id: id(),
    title: "UI/UX Design in the age of AI",
    description: "Explore how AI tools are reshaping product design workflows.",
    statusLabel: "Important",
    priority: "high",
    dueDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    columnId: "todo",
    createdAt: new Date().toISOString(),
  },
  {
    id: id(),
    title: "Responsive website for 23 clients",
    description: "Build a responsive marketing site template that scales across breakpoints.",
    statusLabel: "Meh",
    priority: "medium",
    dueDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    columnId: "todo",
    createdAt: new Date().toISOString(),
  },
  {
    id: id(),
    title: "Blog copywriting (low priority)",
    description: "Draft three blog posts on product updates.",
    statusLabel: "OK",
    priority: "low",
    dueDate: new Date(Date.now() + 14 * 86400000).toISOString(),
    columnId: "todo",
    createdAt: new Date().toISOString(),
  },
  {
    id: id(),
    title: "User flow confirmation for finance app",
    description: "Validate the new onboarding flow with stakeholders.",
    statusLabel: "Important",
    priority: "high",
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    columnId: "in-progress",
    createdAt: new Date().toISOString(),
  },
  {
    id: id(),
    title: "Healthcare app wireframe flow",
    description: "Create low-fi wireframes for the patient dashboard.",
    statusLabel: "On Track",
    priority: "medium",
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    columnId: "in-progress",
    createdAt: new Date().toISOString(),
  },
  {
    id: id(),
    title: "Mobile app bug fixing",
    description: "Identify and fix bugs in the mobile app, ensuring stability.",
    statusLabel: "Complete",
    priority: "high",
    dueDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    columnId: "done",
    createdAt: new Date().toISOString(),
  },
  {
    id: id(),
    title: "Client presentation design",
    description: "Design a polished presentation for the client pitch.",
    statusLabel: "Complete",
    priority: "medium",
    dueDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    columnId: "done",
    createdAt: new Date().toISOString(),
  },
];
